server:
  address: 0.0.0.0
spring:
  application:
    name: app
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: app
    url: jdbc:mysql://localhost:3306/app?serverTimezone=Asia/Seoul
    username: app
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
